baseURL = "/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "ananke"
publishDir = "public"
contentDir = "content"

defaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "My Hugo Blog"
    weight = 1
    languageName = "English"
    contentDir = "content/en" # â† ğŸš¨ ì¶”ê°€!

  [languages.ko]
    title = "ë‚´ íœ´ê³  ë¸”ë¡œê·¸"
    weight = 2
    languageName = "í•œêµ­ì–´"
    contentDir = "content/ko" # â† ğŸš¨ ì¶”ê°€!

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
